version: '3.7'

services:

  db:
    image: wangxian/alpine-mysql
    restart: always
    volumes:
      - ./server/data:/app
    environment:
      - MYSQL_DATABASE=cms
      - MYSQL_USER=root
      - MYSQL_PASSWORD=12341234
      - MYSQL_ROOT_PASSWORD=12345678
    ports:
      - 33060:3306
    networks: 
      - cms_network

  server:
    ports:
      - 4000:4000
    volumes:
      - ./server:/usr/src/app
    build:
      context: ./server
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=12341234
      - DB_PORT=3306
      - DB_DB=cms
    depends_on:
      - db
    networks:
      - cms_network

  client:
    ports:
      - 3000:3000
    volumes:
      - .client:/usr/src/app
    build:
      context: ./client
    environment:
      - API_PORT=4000
      - API_URL=localhost
    depends_on:
      - server
    networks: 
      - cms_network

networks:
  cms_network:
    name: cms_network 
